---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_ansible_repo: true # require ansible
  ansible_verbose: true # enable verbose feedback
  require_chef_for_busser: false # chef is not needed to run the tests
  playbook: site.yml

transport:
  max_ssh_sessions: 6 # to stay below the centos 7 default of 10

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default